openapi: 3.0.3
info:
  title: sh api
  version: n0.1
servers:
  - url: '{api_domain}/api/{api_version}'
    variables:
      api_domain:
        default: 'https://dev.simple-home.liis.su'
        enum:
          - 'https://dev.simple-home.liis.su'
          - 'https://simple-home.liis.su'
          - 'http://localhost:8080'
      api_version:
        default: v2
        enum:
          - v2
          - v1
security:
  - BearerAuth: []
paths:
  '/images/{image_id}':
    delete:
      operationId: image-delete
      description: удаление изображения
      tags:
        - images
      parameters:
        - in: path
          name: image_id
          description: id изображения
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Изображение удалено
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Validation Error
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not found
  /admin/images:
    get:
      operationId: admin-image-list
      description: Получение списка изображений
      tags:
        - images
      parameters:
        - in: query
          name: sort
          required: false
          description: 'Принимает имя поля, по которому необходимо выполнить сортировку. Для изменения порядка сортировки, перед именем поля вставляется символ "-".'
          schema:
            type: string
            example: '-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
    post:
      operationId: admin-image-create
      description: Загрузка изображения
      tags:
        - images
      parameters:
        - in: query
          name: room_id
          required: false
          schema:
            type: integer
        - in: query
          name: account_id
          required: false
          schema:
            type: integer
        - in: query
          name: residence_id
          required: false
          schema:
            type: integer
        - in: query
          name: account_residence_ordering_id
          required: false
          schema:
            type: integer
        - in: query
          name: support_chat_room_id
          required: false
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        '200':
          description: Изображение уже существует в файловом хранилище. Изображение записано в БД
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
        '201':
          description: Изображение загружено в файловое хранилище и записано в БД
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
        '400':
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Validation Error
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Id Must Be An Integer!
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Entity already exists!
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not enough permissions
  /admin/images/templates:
    post:
      operationId: admin-image-template-create
      description: Загрузка изображения в шаблон комнаты (как я понял)
      tags:
        - images
      parameters:
        - in: path
          name: path
          required: true
          description: 'Отражает путь к папке в файловом хранилище, в которой будет сохранено изображение'
          schema:
            type: string
            example: '%2Fimages%2Fresidences%2F4%2Frooms%2Ftemplates%2FАр деко'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
        '400':
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Entity already exists!
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Validation Error
                  - type: object
                    properties:
                      detail:
                        type: string
                        example: Id Must Be An Integer!
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not enough permissions
  '/admin/images/{image_id}':
    get:
      operationId: admin-image-retrieve
      description: Получение изображения
      tags:
        - images
      parameters:
        - in: path
          name: image_id
          description: id изображения
          required: true
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not found
    delete:
      operationId: admin-image-delete
      description: Удаление изображения
      tags:
        - images
      parameters:
        - in: path
          name: image_id
          description: id изображения
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: изображение удалено
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Validation Error
        '403':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not enough permissions
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not found
    put:
      operationId: admin-image-update
      description: Изменение изображения
      tags:
        - images
      parameters:
        - in: '#/components/parameters/imageId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
              required:
                - url
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    example: api/v2/images/hash/7aead86346e6a96620ff0b8c4661d2da
                  file_path:
                    type: string
                    example: /images/account_residence_ordering/3/7aead86346e6a96620ff0b8c4661d2da.jpg
                  hash:
                    type: string
                    example: 7aead86346e6a96620ff0b8c4661d2da
                  residence_id:
                    type: integer
                  updated_at:
                    type: string
                    example: '2021-05-05T05:32:34.598281+00:00'
                required:
                  - id
                  - url
                  - file_path
                  - hash
                  - updated_at
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Entity already exists!
        '404':
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Not found
    components:
      parameters:
        imageId:
          in: path
          name: image_id
          description: id изображения
          required: true
          schema:
            type: integer
